### ISSUE TITLE
Redoing undo

### ISSUE THREAD

**Issue by heymartinadams** [rocicorp/undo#9]
This particular issue may be what @cesara is mentioning in https://github.com/rocicorp/replicache/issues/1008#issuecomment-1286346572, not sure, so reposting here.

```js
const execute = () => rep.mutate.todoCreate({ ...todo })
const undo = () => rep.mutate.todoDelete(todoId)
repUndo.add({ execute, undo })
```

When attempting to `redo` the `undo`, Replicache attempts to create a new task using the same `todo.id` that was used initially.

Wouldn’t be an issue if it weren’t for the fact that the `todoDelete` mutation only soft deletes the record, so creating the same record again causes a duplicate record error.

One solution could perhaps be doing something like: `repUndo.add({ execute, undo, redo })` with `redo()` being an optionally different function (and if not specified, it’s the `execute()` function).

**Comment by aboodman** [comment]
See discord thread here: https://discord.com/channels/830183651022471199/1123000738675703860

In the case you're using a soft deletes on the server, the create mutator on server should be coded to flip deleted bit (and bump version) rather than attempt to recreate.
